import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:timeago/timeago.dart' as timeago;
import '../../../core/theme/app_theme.dart';
import '../../../core/api/api_client.dart';
import '../../../core/api/api_endpoints.dart';

final _demoDemos = [
  {
    '_id': 'demo-1',
    'businessName': 'Al Nakheel Restaurant',
    'businessType': 'restaurant',
    'visitorEmail': 'ahmed@example.com',
    'status': 'generated',
    'primaryColor': '#FF6B35',
    'language': 'ar',
    'createdAt': DateTime.now().subtract(const Duration(minutes: 15)).toIso8601String(),
  },
  {
    '_id': 'demo-2',
    'businessName': 'Smile Dental Clinic',
    'businessType': 'clinic',
    'visitorEmail': 'sara@example.com',
    'status': 'generated',
    'primaryColor': '#00D4FF',
    'language': 'en',
    'createdAt': DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
  },
  {
    '_id': 'demo-3',
    'businessName': 'FitLife Gym',
    'businessType': 'gym',
    'visitorEmail': 'khaled@example.com',
    'status': 'generated',
    'primaryColor': '#6C63FF',
    'language': 'both',
    'createdAt': DateTime.now().subtract(const Duration(hours: 5)).toIso8601String(),
  },
  {
    '_id': 'demo-4',
    'businessName': 'Fashion Store',
    'businessType': 'store',
    'visitorEmail': 'layla@example.com',
    'status': 'generated',
    'primaryColor': '#FF3CAC',
    'language': 'en',
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
  },
];

final aiDemosProvider = FutureProvider<List<Map<String, dynamic>>>((ref) async {
  try {
    final api = ref.read(apiClientProvider);
    final response = await api.get(ApiEndpoints.aiDemos);
    return List<Map<String, dynamic>>.from(response.data['data']);
  } catch (_) {
    return _demoDemos;
  }
});

class AiDemosScreen extends ConsumerWidget {
  const AiDemosScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final demos = ref.watch(aiDemosProvider);

    return Container(
      decoration: const BoxDecoration(gradient: AppTheme.bgGradient),
      child: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: AppTheme.accent.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Icon(Icons.auto_awesome_rounded,
                            color: AppTheme.accent, size: 22),
                      ),
                      const SizedBox(width: 12),
                      Text('AI Demos',
                          style: Theme.of(context).textTheme.displaySmall),
                    ],
                  ),
                  const SizedBox(height: 6),
                  Text(
                    'Websites generated by the AI engine',
                    style: Theme.of(context)
                        .textTheme
                        .bodySmall
                        ?.copyWith(color: AppTheme.textMuted),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 20),

            // List
            Expanded(
              child: demos.when(
                data: (list) => list.isEmpty
                    ? _EmptyAiState()
                    : ListView.builder(
                        padding: const EdgeInsets.fromLTRB(16, 0, 16, 80),
                        itemCount: list.length,
                        itemBuilder: (_, i) => _DemoCard(demo: list[i]),
                      ),
                loading: () => const Center(
                    child: CircularProgressIndicator(color: AppTheme.accent)),
                error: (_, __) => _EmptyAiState(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _DemoCard extends StatelessWidget {
  final Map<String, dynamic> demo;
  const _DemoCard({required this.demo});

  static const _typeIcons = {
    'restaurant': Icons.restaurant_rounded,
    'clinic': Icons.local_hospital_rounded,
    'gym': Icons.fitness_center_rounded,
    'store': Icons.store_rounded,
    'hotel': Icons.hotel_rounded,
    'salon': Icons.content_cut_rounded,
  };

  static const _typeColors = {
    'restaurant': AppTheme.accentOrange,
    'clinic': AppTheme.accent,
    'gym': AppTheme.primary,
    'store': AppTheme.accentPink,
    'hotel': AppTheme.accentGreen,
    'salon': AppTheme.accentPink,
  };

  @override
  Widget build(BuildContext context) {
    final type = demo['businessType'] as String? ?? 'store';
    final icon = _typeIcons[type] ?? Icons.web_rounded;
    final color = _typeColors[type] ?? AppTheme.primary;
    final primaryColor = demo['primaryColor'] as String? ?? '#6C63FF';
    final createdAt = demo['createdAt'] != null
        ? DateTime.tryParse(demo['createdAt'])
        : null;
    final lang = demo['language'] as String? ?? 'en';

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.bgCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.border),
        boxShadow: AppTheme.cardShadow,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 46,
                height: 46,
                decoration: BoxDecoration(
                  color: color.withOpacity(0.15),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, color: color, size: 22),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      demo['businessName'] ?? 'Unknown',
                      style: const TextStyle(
                        fontFamily: 'Outfit',
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                        color: AppTheme.textPrimary,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      demo['visitorEmail'] ?? '',
                      style: const TextStyle(
                        fontFamily: 'Outfit',
                        fontSize: 12,
                        color: AppTheme.textMuted,
                      ),
                    ),
                  ],
                ),
              ),
              // Generated badge
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: AppTheme.success.withOpacity(0.12),
                  borderRadius: BorderRadius.circular(6),
                  border: Border.all(color: AppTheme.success.withOpacity(0.2)),
                ),
                child: const Text(
                  '✓ Generated',
                  style: TextStyle(
                    fontFamily: 'Outfit',
                    fontSize: 11,
                    fontWeight: FontWeight.w600,
                    color: AppTheme.success,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          const Divider(color: AppTheme.border, height: 1),
          const SizedBox(height: 12),
          Row(
            children: [
              _Tag(label: type, color: color),
              const SizedBox(width: 8),
              _Tag(label: lang.toUpperCase(), color: AppTheme.primary),
              const SizedBox(width: 8),
              Container(
                width: 16,
                height: 16,
                decoration: BoxDecoration(
                  color: Color(
                      int.parse(primaryColor.replaceAll('#', '0xFF'))),
                  shape: BoxShape.circle,
                  border: Border.all(color: AppTheme.border),
                ),
              ),
              const Spacer(),
              Text(
                createdAt != null ? timeago.format(createdAt) : '',
                style: const TextStyle(
                  fontFamily: 'Outfit',
                  fontSize: 11,
                  color: AppTheme.textMuted,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: _ActionBtn(
                  label: 'View Demo',
                  icon: Icons.open_in_browser_rounded,
                  color: AppTheme.accent,
                  onTap: () {},
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _ActionBtn(
                  label: 'Contact Client',
                  icon: Icons.chat_rounded,
                  color: AppTheme.primary,
                  onTap: () {},
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Tag extends StatelessWidget {
  final String label;
  final Color color;
  const _Tag({required this.label, required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(6),
      ),
      child: Text(
        label,
        style: TextStyle(
          fontFamily: 'Outfit',
          fontSize: 11,
          fontWeight: FontWeight.w600,
          color: color,
        ),
      ),
    );
  }
}

class _ActionBtn extends StatelessWidget {
  final String label;
  final IconData icon;
  final Color color;
  final VoidCallback onTap;
  const _ActionBtn({
    required this.label,
    required this.icon,
    required this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 10),
        decoration: BoxDecoration(
          color: color.withOpacity(0.1),
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: color.withOpacity(0.25)),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, color: color, size: 16),
            const SizedBox(width: 6),
            Text(
              label,
              style: TextStyle(
                fontFamily: 'Outfit',
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _EmptyAiState extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.auto_awesome_rounded, color: AppTheme.accent, size: 48),
          SizedBox(height: 12),
          Text('No AI demos yet',
              style: TextStyle(
                  fontFamily: 'Outfit',
                  color: AppTheme.textPrimary,
                  fontSize: 18,
                  fontWeight: FontWeight.w600)),
          SizedBox(height: 6),
          Text('Generated demos will appear here',
              style: TextStyle(
                  fontFamily: 'Outfit',
                  color: AppTheme.textMuted,
                  fontSize: 13)),
        ],
      ),
    );
  }
}
