// POST /api/export
// Splits a generated single-file HTML page into separate
// index.html / style.css / script.js + a README and bundles as ZIP.

import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'

export const runtime = 'nodejs'

interface Body {
  html: string
  projectName?: string
}

export async function POST(req: NextRequest) {
  let body: Body
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const fullHtml = (body.html || '').trim()
  if (!fullHtml || fullHtml.length < 50) {
    return NextResponse.json({ error: 'Missing or invalid html' }, { status: 400 })
  }
  const projectName = (body.projectName || 'vixcell-site').slice(0, 80)

  // Pull out <style>…</style> and <script>…</script>
  const styleMatch  = fullHtml.match(/<style[^>]*>([\s\S]*?)<\/style>/i)
  const scriptMatch = fullHtml.match(/<script[^>]*>([\s\S]*?)<\/script>/i)

  const css = styleMatch  ? styleMatch[1].trim()  : ''
  const js  = scriptMatch ? scriptMatch[1].trim() : ''

  // Strip those tags from the HTML and replace with file references
  let html = fullHtml
    .replace(/<style[^>]*>[\s\S]*?<\/style>/i, css ? '<link rel="stylesheet" href="style.css">' : '')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/i, js ? '<script src="script.js"></script>' : '')

  // Ensure indentation/whitespace is reasonable
  html = html.trim() + '\n'

  const zip = new JSZip()
  zip.file('index.html', html)
  if (css) zip.file('style.css',  css + '\n')
  if (js)  zip.file('script.js',  js  + '\n')

  zip.file('README.md', buildReadme(projectName))

  const buf = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE', compressionOptions: { level: 6 } })

  return new NextResponse(buf, {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${slugify(projectName)}.zip"`,
      'Cache-Control': 'no-store',
    },
  })
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'site'
}

function buildReadme(projectName: string): string {
  return `# ${projectName}

Generated by **VIXCELL AI** — [vixcell.com](https://vixcell.com)

## Files
- \`index.html\` — Semantic HTML5 markup
- \`style.css\`  — Stylesheet (CSS variables, responsive)
- \`script.js\`  — Animations, smooth scroll, intersection observer

## Run locally
Just open \`index.html\` in a browser, or run any static server:
\`\`\`bash
npx serve .
# or
python3 -m http.server 8000
\`\`\`

## Deploy
Drop the folder onto any of these:
- [Vercel](https://vercel.com) — \`vercel\`
- [Netlify](https://netlify.com) — drag & drop
- [Cloudflare Pages](https://pages.cloudflare.com)
- [GitHub Pages](https://pages.github.com)

## Customize
Edit \`style.css\` to tweak colors (CSS variables at the top) or come back to
[vixcell.com/builder](https://vixcell.com/builder) and generate a fresh variant.
`
}
